/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/animatedIronMan.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.01, 0.12, -0.69]} rotation={[-2.92, -0.02, -0.01]} scale={[17.2, 13.64, 13.65]}>
            <mesh geometry={nodes.mesh_id121_001_10_0.geometry} material={materials.mesh_id121_001} />
          </group>
          <group position={[0.01, -0.09, -0.1]} rotation={[-0.27, -0.01, -0.01]} scale={[15.31, 13.64, 13.64]}>
            <mesh geometry={nodes.mesh_id123_002_13_0.geometry} material={materials.mesh_id123_002} />
          </group>
          <group position={[0.02, -0.04, -0.14]} rotation={[-1.53, -0.02, -0.02]} scale={[17.2, 13.64, 13.64]}>
            <mesh geometry={nodes.mesh_id123_16_0.geometry} material={materials.mesh_id123} />
          </group>
          <group position={[0.1, -0.27, 0.21]} rotation={[2.34, -0.42, -0.34]} scale={[14.89, 13.8, 13.95]}>
            <mesh geometry={nodes.mesh_id123_003_19_0.geometry} material={materials.mesh_id123_003} />
          </group>
          <group position={[-0.1, -0.27, 0.2]} rotation={[2.33, 0.44, 0.37]} scale={[14.88, 13.79, 13.96]}>
            <mesh geometry={nodes.mesh_id123_005_22_0.geometry} material={materials.mesh_id123_005} />
          </group>
          <group position={[0.02, -0.02, -0.09]} rotation={[-0.93, -0.02, -0.02]} scale={[17.2, 13.64, 13.64]}>
            <mesh geometry={nodes.mesh_id123_004_25_0.geometry} material={materials.mesh_id123_004} />
          </group>
          <group position={[0.01, 0.37, -0.38]} rotation={[-2.31, -0.02, -0.01]} scale={[17.2, 13.64, 13.65]}>
            <mesh geometry={nodes.mesh_id121_004_28_0.geometry} material={materials.mesh_id121_004} />
          </group>
          <group position={[-0.1, -0.27, 0.2]} rotation={[2.33, 0.44, 0.37]} scale={[14.88, 13.79, 13.96]}>
            <mesh geometry={nodes.mesh_id123_012_31_0.geometry} material={materials.mesh_id123_012} />
          </group>
          <group
            name="Object_45"
            position={[0.1, -0.27, 0.21]}
            rotation={[2.34, -0.42, -0.34]}
            scale={[14.89, 13.8, 13.95]}>
            <mesh geometry={nodes.mesh_id123_013_34_0.geometry} material={materials.mesh_id123_013} />
          </group>
          <group position={[0.01, 0.37, -0.38]} rotation={[-2.31, -0.02, -0.01]} scale={[17.2, 13.64, 13.65]}>
            <mesh geometry={nodes.mesh_id121_3_0.geometry} material={materials.mesh_id121} />
          </group>
          <group position={[0, 0.02, -0.13]} scale={[13.64, 13.64, 13.64]}>
            <mesh geometry={nodes.mesh_id123_001_7_0.geometry} material={materials.mesh_id123_001} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/animatedIronMan.glb')
