/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useLoader } from "@react-three/fiber";
import { TextureLoader } from "three";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    process.env.PUBLIC_URL + "/sheet.glb"
  );
  const { actions } = useAnimations(animations, group);

  const front = useLoader(TextureLoader, process.env.PUBLIC_URL + "/front.jpg");
  front.flipY = false;
  const back = useLoader(TextureLoader, process.env.PUBLIC_URL + "/back.jpg");
  back.flipY = false;

  useEffect(() => {
    // console.log("sheet actions: ", actions);
    // const { toSheet } = actions;
    // toSheet.repetitions = 1;
    // toSheet.clampWhenFinished = true;
    // toSheet.play();
  }, []);

  return (
    <group
      position={[12, -0.6, 682]}
      // scale={[0.4, 0.4, 0.4]}
      rotation={[0, Math.PI / 8, 0]}
      ref={group}
      {...props}
      dispose={null}
    >
      <mesh
        name="material"
        geometry={nodes.material.geometry}
        morphTargetDictionary={nodes.material.morphTargetDictionary}
        morphTargetInfluences={nodes.material.morphTargetInfluences}
      >
        <meshStandardMaterial
          {...nodes.material.material}
          map={back}
          roughness={1}
          metalness={0.4}
          transparent={true}
          depthTest={true}
          alphaTest={0.5}
        />
      </mesh>
      <mesh
        name="material_1"
        geometry={nodes.material_1.geometry}
        morphTargetDictionary={nodes.material_1.morphTargetDictionary}
        morphTargetInfluences={nodes.material_1.morphTargetInfluences}
      >
        <meshStandardMaterial
          {...nodes.material_1.material}
          map={front}
          roughness={1}
          metalness={0.4}
          transparent={true}
          depthTest={true}
          alphaTest={0.5}
        />
      </mesh>
      <mesh
        name="material_2"
        geometry={nodes.material_2.geometry}
        morphTargetDictionary={nodes.material_2.morphTargetDictionary}
        morphTargetInfluences={nodes.material_2.morphTargetInfluences}
      >
        <meshStandardMaterial
          {...nodes.material_2.material}
          color="#fff"
          emissive="#fff"
        />
      </mesh>
    </group>
  );
}

useGLTF.preload(process.env.PUBLIC_URL + "/sheet.glb");
